

# Define a user-defined bridge network
networks:
  my_ros_network:
    driver: bridge

services:
  moveit2:
    image: moveit/moveit2:rolling-release
    #image: moveit/moveit2:main-rolling-tutorial-source
    container_name: moveit2_container
    privileged: true
    # Use the user-defined network instead of host network
    # network_mode: host # Removed
    networks:
      - my_ros_network
    command: tail -f /dev/null  # This will keep the container running indefinitely
     #command: sh -c "python3 /shared_with_docker/socket_server.py" # <--- This is key for the server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
      - ../shared_with_docker:/shared_with_docker
      #- ./cyclonedds.xml:/cyclonedds.xml:ro  # Mount the DDS configuration
    devices:
      - /dev:/dev
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      #ROS_DOMAIN_ID: 42  # Ensures both containers are in the same ROS domain
      #CYCLONEDDS_URI: file:///cyclonedds.xml

  # YOLO Container for object detection
  yoloros2:
    image: yoloros2/test3:latest  # Base image with YOLO     docker pull elettronicaopensource/yolo_ros2_opencv_gstreamer:test2
    container_name: yoloros2_container
    privileged: true
    # Use the user-defined network instead of host network
    # network_mode: host # Removed
    networks:
      - my_ros_network
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # For GUI if needed
      - $XAUTHORITY:/root/.Xauthority
      #- ./cyclonedds.xml:/cyclonedds.xml:ro  # Mount the DDS configuration
      - ./yolo_ws:/yolo_ws  # Mount your YOLO workspace
      - ../shared_with_docker:/shared_with_docker  # Share data with MoveIt2
      - /dev/video0:/dev/video0  # Camera access (adjust device as needed)
      - /dev/:/dev/ 
    devices:
      - /dev/video0:/dev/video0  # Camera device pass-through
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      #ROS_DOMAIN_ID: 42  # Ensures both containers are in the same ROS domain
      #CYCLONEDDS_URI: file:///cyclonedds.xml
