#docker-compose run --rm moveit2
#docker-compose run --rm yoloros2

services:
  moveit2:
    #image: moveit/moveit2:main-jazzy-tutorial-source
    image: moveit/moveit2:main-rolling-tutorial-source
    container_name: moveit2_container
    privileged: true
    network_mode: host
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
      - /media/data/progetti/neural_gripper/neuralgripper/moveit2_docker/shared_with_docker:/shared_with_docker
      - ./cyclonedds.xml:/cyclonedds.xml:ro  # Mount the DDS configuration
    devices:
      - /dev:/dev
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      ROS_DOMAIN_ID: 42  # Ensures both containers are in the same ROS domain
      CYCLONEDDS_URI: file:///cyclonedds.xml
  
  # YOLO Container for object detection
  yoloros2:
    image: yoloros2/test2  # Base image with YOLO
    container_name: yoloros2_container
    privileged: true
    network_mode: host  # Use host network for optimal ROS 2 communication
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # For GUI if needed
      - $XAUTHORITY:/root/.Xauthority
      - ./cyclonedds.xml:/cyclonedds.xml:ro  # Mount the DDS configuration
      - ./yolo_ws:/yolo_ws  # Mount your YOLO workspace
      - /media/data/progetti/neural_gripper/neuralgripper/moveit2_docker/shared_with_docker:/shared_with_docker  # Share data with MoveIt2
      - /dev/video0:/dev/video0  # Camera access (adjust device as needed)
    devices:
      - /dev/video0:/dev/video0  # Camera device pass-through
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      ROS_DOMAIN_ID: 42  # Ensures both containers are in the same ROS domain
      CYCLONEDDS_URI: file:///cyclonedds.xml
      
      
